[package]
name = "cytocount"
version = "0.1.0"
edition = "2021"

[dependencies]
imageproc = "0.25.0"
papillae = { git = "https://github.com/nstone8/papillae", version = "0.1.9" }
recbudd = { git = "https://github.com/nstone8/recbudd", version = "0.1.4" }
